### ISSUE TITLE
Bug: when launching for the first time, window is not sized correctly 

### ISSUE THREAD

**Issue by sambacha** [fxfactorial/evm-dev-station#1]
When launching for the first time, the window is not sized to display the entire GUI 

<img width="774" alt="Screenshot 2023-11-07 at 9 16 38 PM" src="https://github.com/fxfactorial/evm-dev-station/assets/32783916/b1bdecda-ffba-4370-a454-07d527df4331">

**Comment by fxfactorial** [comment]
thank you so much for trying and your patience - can you pull and try again. 

(There is known animation problem on top folding )

**Comment by sambacha** [comment]
Fixed

<img width="1949" alt="Screenshot 2023-11-08 at 11 13 37 PM" src="https://github.com/fxfactorial/evm-dev-station/assets/32783916/3ce4ceb4-f57a-4863-be47-5b222a6616e5">
