### ISSUE TITLE
Create a Universal Binary instead of two separate binaries

### ISSUE THREAD

**Issue by sambacha** [fxfactorial/evm-dev-station#2]
Maintaining two separate binaries is unnecessary now with the way you can make a smaller Universal Binary out of the two build outputs.

**Comment by fxfactorial** [comment]
okay cool this is a good idea , i will play with it. apparently as easy as `    lipo -create -output universal_app x86_app arm_app`

**Comment by fxfactorial** [comment]
k, done. ofc it doubled the binary size now to 41 mb but whatever doesn't really matter in this case
